# Site settings
title: First birds
description: Ommestrup & Omegns Automobil Klub
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "http://firstbirds.dk"

# User settings
username: First birds
user_description: First birds er en gruppe af ellers rimeligt normale og velfungerende samfundsborgere fra Ommestrup og omegn. Afvigelsen fra det normale er fascinationen af automobiler produceret i Guds eget land i det forrige århundrede, med go'e gammeldags støbejerns V-8'ere der bruger masser af benzin og skal skrues i konstant.
user_title: Ommestrup & Omegns Automobil Klub

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
